### ISSUE TITLE
Tech Table

### ISSUE THREAD

**Issue by mmf62208** [Wugand/FuturePack-Language#138]
Unable to use tech table after researching the 12 elements is there something else that you must do to be able to use it?

**Comment by mcenderdragon** [comment]
This is the lagugae repository and not the main mod repository

**Comment by mcenderdragon** [comment]
https://github.com/mcenderdragon/Futurepack-API/issues/207

**Comment by mcenderdragon** [comment]
This can be closed @Wugand
