### ISSUE TITLE
wrong meneluas entityy reasearch translation for english

### ISSUE THREAD

**Issue by mcenderdragon** [Wugand/FuturePack-Language#173]
> Hm... why crawler looks like the seal?.. As wrote in research

> n the german version there is the word "Heuler" which would directly translated mean something like  "someone who is howling". "Heuler" is referencing to the flying insects which eat the fireflies at night. I dont know why it is wrongly translated
> is "Howler" is correct word ?

**Comment by a22brad22** [comment]
I don't see the word Howler anywhere in the text. Is this an English or German issue?
A seal is indeed a Seehund/Heuler

**Comment by mcenderdragon** [comment]
yeah abd seal is thw wrong word which needs to be rplaced with Howler/Heuler.

**Comment by a22brad22** [comment]
Got it. I fixed the text!

**Comment by mcenderdragon** [comment]
just noticed it: if you mention a issue or PR in a commit use # befire it so github will link it properly like #173

**Comment by a22brad22** [comment]
Oh! Sorry, this project is the only one I work on in github so I don't really know how this kind of thing works. I'll do that from now on.
