### ISSUE TITLE
decoration text is missleading 

### ISSUE THREAD

**Issue by mcenderdragon** [Wugand/FuturePack-Language#176]
see https://www.reddit.com/r/feedthebeast/comments/bjmtrm/futurepack_grinding_surfaces_of_metal_blocks

>  It says that I can grind the surfaces of metal blocks to make them plain and simple, but there is nothing about how can i do that.

>its airbrush, you can paint with it and remove paint bu putting sand in it, but it only works with decoloring colored metal blocks and other stuff, it doesnt work on a metal block

**Comment by a22brad22** [comment]
I fixed the text for this to make it less ambiguous.
